# Generated by Django 5.0.4 on 2024-04-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prize_images/')),
                ('prize_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('is_sold', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
