# Generated by Django 5.0.4 on 2024-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0003_alter_people_signup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='signup_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
