# Generated by Django 5.0.4 on 2024-04-07 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applet', '0004_alter_people_signup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Event date'),
        ),
    ]
